### PR TITLE
Add shared library

### PR DESCRIPTION
**Pull request by elbaro**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by elbaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Hi @elbaro, sorry for the late reply but I just became a mantainer of the feedstock. If you are still interested in this, could you explain the rationale for this change? From what I understand, `backward` is meant to be an header only library, and the static/shared library in the CMake project is not installed and not mentioned at all in the `BackwardConfig.cmake` file.

**Comment by elbaro** [comment]
The `README.md` mentions about `backward.cpp` which provides additional features.

`CMakeLists.txt` provides the flag to build a shared version:
https://github.com/bombela/backward-cpp/blob/master/CMakeLists.txt#L78-L88

I am not actively using `backward-cpp` now, so feel free to close or take over and update the PR.

**Comment by traversaro** [comment]
> The `README.md` mentions about `backward.cpp` which provides additional features.

The README however suggest to directly include the `backward.cpp` file in your project, not to build the shared library and link it, as in fact there is no support for finding it and link it via CMake. If no one is interested in this at the moment, let's close it.

**Pull request closed without merging**
